str1 = "AbcdEFGhi"
print("print str in upper case:", str1.upper())
print("print str1 in lower case:" ,str1.lower())
print("print str1 in title case:", str1.capitalize())
str2 = "  Pranita Kamble "
print("Remove spaces from string:", str2.strip() )
print(":",str2)
print("Remove right space from str2:", str2.rstrip())
print("Remove left space from str2:", str2.lstrip())

print("Replace the str2 with Sonepari:", str2.replace(str2 ,"Sonpari"))
print("split the str2 in to two string:", str2.split())
print("diplay str1 as title:", str1.title())
print("display the slipted str2:" , str2.split())
print("print str2 at center:", str2.center(90))
print("print number of a's at str2:", str2.count("P"))
print(str2.endswith(" "))
print(str2.find("Pra"))
print("retun index:", str2.index("P"))
print("isalnum:",str2.isalnum())
print("isalpha:", str2.isalpha())
print("islower:",str2.islower())
print("isupper:",str2.isupper())
print("isprintable:", str2.isprintable())
print("isspace:", str2.isspace())
print("istitle:",str2.istitle())
str3 = "Python is compiled language"
print("Replace string:",str3.replace("compiled", "Interpreted"))
print("startswith:", str3.startswith("Python"))
print("swapcase:", str3.swapcase())
print("title:", str3.title())